# Generated by Django 5.1.6 on 2025-02-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle', models.CharField(choices=[('car', 'Car'), ('two wheeler', 'Two wheeler'), ('cycle', 'Cycle')], default='car', max_length=50)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('event_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=15, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('parking_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.parkingspace')),
            ],
        ),
    ]
