# Generated by Django 5.1.6 on 2025-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('two wheeler', 'Two wheeler'), ('cycle', 'Cycle')], default='car', max_length=50),
        ),
    ]
