# Generated by Django 5.1.6 on 2025-02-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_parkingspace_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspace',
            old_name='area',
            new_name='parking_area',
        ),
    ]
