# Generated by Django 5.1.6 on 2025-02-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_parkingspace_parking_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parking_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
