# Generated by Django 5.1.6 on 2025-02-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_parkingspace_parking_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='event_datetime',
        ),
    ]
