# Generated by Django 5.1.6 on 2025-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_parkingspace_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
